### ISSUE TITLE
allow multiple `--target` url values for failover cases

### ISSUE THREAD

**Issue by rampall** [ethersphere/etherproxy#16]
multiple `--target` url values pointing to multiple nodes can gracefully handle failover cases when 
- a node is waiting to sync 
- a node is migrating
- request timed out etc

**Comment by rampall** [comment]
Reference: Out of requests error from getblock

2023-10-06T12:09:13: TypeError: Cannot create property 'id' on string 'Out of requests'
2023-10-06T12:09:13:     at /home/rp/.nvm/versions/node/v20.8.0/lib/node_modules/etherproxy/dist/utility.js:33:25
2023-10-06T12:09:13:     at Generator.next (<anonymous>)
2023-10-06T12:09:13:     at fulfilled (/home/rp/.nvm/versions/node/v20.8.0/lib/node_modules/etherproxy/dist/utility.js:5:58)
2023-10-06T12:09:13:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
