### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by rampall** [ethersphere/etherproxy#17]
ethproxy-error.log

2023-10-02T12:29:18: SyntaxError: Unexpected end of JSON input
2023-10-02T12:29:18:     at JSON.parse (<anonymous>)
2023-10-02T12:29:18:     at /home/rp/.nvm/versions/node/v18.16.0/lib/node_modules/etherproxy/dist/index.js:52:41
2023-10-02T12:29:18:     at Generator.next (<anonymous>)
2023-10-02T12:29:18:     at /home/rp/.nvm/versions/node/v18.16.0/lib/node_modules/etherproxy/dist/index.js:9:71
2023-10-02T12:29:18:     at new Promise (<anonymous>)
2023-10-02T12:29:18:     at __awaiter (/home/rp/.nvm/versions/node/v18.16.0/lib/node_modules/etherproxy/dist/index.js:5:12)
2023-10-02T12:29:18:     at IncomingMessage.<anonymous> (/home/rp/.nvm/versions/node/v18.16.0/lib/node_modules/etherproxy/dist/index.js:44:33)
2023-10-02T12:29:18:     at IncomingMessage.emit (node:events:513:28)
2023-10-02T12:29:18:     at endReadableNT (node:internal/streams/readable:1359:12)
2023-10-02T12:29:18:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-10-02T12:29:18: SyntaxError: Unexpected end of JSON input
2023-10-02T12:29:18:     at JSON.parse (<anonymous>)
2023-10-02T12:29:18:     at /home/rp/.nvm/versions/node/v18.16.0/lib/node_modules/etherproxy/dist/index.js:52:41
2023-10-02T12:29:18:     at Generator.next (<anonymous>)
2023-10-02T12:29:18:     at /home/rp/.nvm/versions/node/v18.16.0/lib/node_modules/etherproxy/dist/index.js:9:71
2023-10-02T12:29:18:     at new Promise (<anonymous>)
2023-10-02T12:29:18:     at __awaiter (/home/rp/.nvm/versions/node/v18.16.0/lib/node_modules/etherproxy/dist/index.js:5:12)
2023-10-02T12:29:18:     at IncomingMessage.<anonymous> (/home/rp/.nvm/versions/node/v18.16.0/lib/node_modules/etherproxy/dist/index.js:44:33)
2023-10-02T12:29:18:     at IncomingMessage.emit (node:events:513:28)
2023-10-02T12:29:18:     at endReadableNT (node:internal/streams/readable:1359:12)
2023-10-02T12:29:18:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-10-02T12:51:31: SyntaxError: Unexpected end of JSON input
2023-10-02T12:51:31:     at JSON.parse (<anonymous>)
2023-10-02T12:51:31:     at /home/rp/.nvm/versions/node/v18.16.0/lib/node_modules/etherproxy/dist/index.js:52:41
2023-10-02T12:51:31:     at Generator.next (<anonymous>)
2023-10-02T12:51:31:     at /home/rp/.nvm/versions/node/v18.16.0/lib/node_modules/etherproxy/dist/index.js:9:71
2023-10-02T12:51:31:     at new Promise (<anonymous>)
2023-10-02T12:51:31:     at __awaiter (/home/rp/.nvm/versions/node/v18.16.0/lib/node_modules/etherproxy/dist/index.js:5:12)
2023-10-02T12:51:31:     at IncomingMessage.<anonymous> (/home/rp/.nvm/versions/node/v18.16.0/lib/node_modules/etherproxy/dist/index.js:44:33)
2023-10-02T12:51:31:     at IncomingMessage.emit (node:events:513:28)
2023-10-02T12:51:31:     at endReadableNT (node:internal/streams/readable:1359:12)
2023-10-02T12:51:31:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by rampall** [comment]
ethproxy-out.log

2023-10-02T12:29:14: [~] Key: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:14: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:14: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Key: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
2023-10-02T12:29:17: [~] Cache hit: {"jsonrpc":"2.0","method":"eth_blockNumber"}
